### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by Kaahbal** [AaronDavidSchneider/SonosAlarmAutomation#1]
With 0.118 this seem to have stopped working. Alarm no longer triggers when set through Hassio

**Comment by AaronDavidSchneider** [comment]
Please post log entries and test restarting of homeassistant.

**Comment by Kaahbal** [comment]
Cannot see anything in logs. Have restarted everything including servers and the affected Sonos speaker, no luck. When i set a new time or switch mode i get device updated but time etc stays the same in both HA and Sonos

**Comment by Kaahbal** [comment]
Resolved it, somehow i had a malfunction in appdaemon, not related to your code.
